In [1]:
import pandas as pd

In [23]:
data = pd.read_csv('TADPOLE_D1_D2.csv')

/Users/aidenarnold/miniconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (471,473,474,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,569,570,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,599,601,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,624,625,626,627,628,629,630,631,632,633,634,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,739,745,746,748,749,750,751,752,753,754,755,756,757,758,759,760,761,762,763,764,765,766,767,770,771,776,777,778,779,780,781,782,783,784,785,786,787,788,789,790,791,794,795,797,798,799,800,801,802,803,804,806,807,808,809,810,811,812,813,814,815,816,817,818,819,820,821,822,823,824,825,826,827,828,829,830,831) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
data.shape

(12741, 1907)

In [4]:
data.tail(20)

,RID,PTID,VISCODE,SITE,D1,D2,COLPROT,ORIGPROT,EXAMDATE,DX_bl,...,PHASE_UPENNBIOMK9_04_19_17,BATCH_UPENNBIOMK9_04_19_17,KIT_UPENNBIOMK9_04_19_17,STDS_UPENNBIOMK9_04_19_17,RUNDATE_UPENNBIOMK9_04_19_17,ABETA_UPENNBIOMK9_04_19_17,TAU_UPENNBIOMK9_04_19_17,PTAU_UPENNBIOMK9_04_19_17,COMMENT_UPENNBIOMK9_04_19_17,update_stamp_UPENNBIOMK9_04_19_17
12721,2213,127_S_2213,m72,127,1,1,ADNI2,ADNIGO,2016-12-08,EMCI,...,,,,,,,,,,
12722,2234,127_S_2234,m72,127,1,1,ADNI2,ADNIGO,2016-12-09,EMCI,...,,,,,,,,,,
12723,4205,099_S_4205,m60,99,1,1,ADNI2,ADNI2,2016-12-08,EMCI,...,,,,,,,,,,
12724,4356,135_S_4356,m60,135,1,1,ADNI2,ADNI2,2016-12-12,EMCI,...,,,,,,,,,,
12725,555,035_S_0555,m120,35,1,1,ADNI2,ADNI1,2016-12-14,CN,...,,,,,,,,,,
12726,1023,036_S_1023,m108,36,1,1,ADNI2,ADNI1,2017-01-10,CN,...,,,,,,,,,,
12727,5263,032_S_5263,m24,32,1,0,ADNI2,ADNI2,2017-01-17,SMC,...,,,,,,,,,,
12728,1032,127_S_1032,m120,127,1,1,ADNI2,ADNI1,2016-11-30,LMCI,...,,,,,,,,,,
12729,4287,129_S_4287,m60,129,1,1,ADNI2,ADNI2,2016-10-28,LMCI,...,,,,,,,,,,
12730,296,100_S_0296,m120,100,1,1,ADNI2,ADNI1,2017-01-24,LMCI,...,,,,,,,,,,
12731,1286,100_S_1286,m108,100,1,1,ADNI2,ADNI1,2017-01-25,CN,...,,,,,,,,,,
12732,4621,153_S_4621,m48,153,1,1,ADNI2,ADNI2,2016-04-25,EMCI,...,,,,,,,,,,
12733,2061,035_S_2061,m72,35,1,1,ADNI2,ADNIGO,2016-09-14,EMCI,...,,,,,,,,,,
12734,4556,100_S_4556,m48,100,1,1,ADNI2,ADNI2,2017-01-30,EMCI,...,,,,,,,,,,
12735,2079,098_S_2079,m72,98,1,1,ADNI2,ADNIGO,2016-12-12,EMCI,...,,,,,,,,,,
12736,4167,116_S_4167,m60,116,1,1,ADNI2,ADNI2,2016-11-16,LMCI,...,,,,,,,,,,
12737,4199,116_S_4199,m60,116,1,1,ADNI2,ADNI2,2016-12-12,EMCI,...,,,,,,,,,,
12738,4557,053_S_4557,m60,53,1,1,ADNI2,ADNI2,2017-03-15,EMCI,...,,,,,,,,,,
12739,4512,100_S_4512,m48,100,1,1,ADNI2,ADNI2,2017-04-04,EMCI,...,,,,,,,,,,
12740,2380,036_S_2380,m72,36,1,1,ADNI2,ADNIGO,2017-05-05,EMCI,...,,,,,,,,,,

In [38]:
d.loc[0:20, ['D1', 'D2', 'VISCODE', 'EXAMDATE', 'Ventricles', 'Ventricles_bl', 'sum']]

    D1  D2 VISCODE    EXAMDATE  Ventricles  Ventricles_bl  sum
0    1   1      bl  2005-09-08    118233.0       118233.0  NaN
1    1   0      bl  2005-09-12     84599.0        84599.0  NaN
2    1   0     m06  2006-03-13     88580.0        84599.0  NaN
3    1   0     m12  2006-09-12     90099.0        84599.0  NaN
4    1   0     m24  2007-09-12     97420.0        84599.0  NaN
5    1   0      bl  2005-11-08     39605.0        39605.0  NaN
6    1   0     m06  2006-05-02     39726.0        39605.0  NaN
7    1   0     m12  2006-11-14     38527.0        39605.0  NaN
8    1   0     m18  2007-05-14     40768.0        39605.0  NaN
9    1   0     m36  2008-11-18     45254.0        39605.0  NaN
10   1   0      bl  2005-09-07     34062.0        34062.0  NaN
11   1   0     m06  2006-03-09     34119.0        34062.0  NaN
12   1   0     m12  2006-09-05     35333.0        34062.0  NaN
13   1   0     m24  2007-09-07     37853.0        34062.0  NaN
14   1   0     m36  2008-09-10     41656.0        34062.0  NaN
15   1   0      bl  2005-11-29     39826.0        39826.0  NaN
16   1   0     m06  2006-06-01     40165.0        39826.0  NaN
17   1   0     m12  2006-11-20     40676.0        39826.0  NaN
18   1   0     m18  2007-05-15     41170.0        39826.0  NaN
19   1   0     m36  2008-12-08     46549.0        39826.0  NaN
20   1   0      bl  2005-10-06     25704.0        25704.0  NaN

In [33]:
ventricles = ['ST127SV_UCSFFSX_11_02_15_UCSFFSX51_08_01_16',
              'ST30SV_UCSFFSX_11_02_15_UCSFFSX51_08_01_16',
              'ST37SV_UCSFFSX_11_02_15_UCSFFSX51_08_01_16',
              'ST89SV_UCSFFSX_11_02_15_UCSFFSX51_08_01_16',
              'ST8SV_UCSFFSX_11_02_15_UCSFFSX51_08_01_16',
              'ST96SV_UCSFFSX_11_02_15_UCSFFSX51_08_01_16',
              'ST9SV_UCSFFSX_11_02_15_UCSFFSX51_08_01_16']

In [39]:
data[ventricles]

,ST127SV_UCSFFSX_11_02_15_UCSFFSX51_08_01_16,ST30SV_UCSFFSX_11_02_15_UCSFFSX51_08_01_16,ST37SV_UCSFFSX_11_02_15_UCSFFSX51_08_01_16,ST89SV_UCSFFSX_11_02_15_UCSFFSX51_08_01_16,ST8SV_UCSFFSX_11_02_15_UCSFFSX51_08_01_16,ST96SV_UCSFFSX_11_02_15_UCSFFSX51_08_01_16,ST9SV_UCSFFSX_11_02_15_UCSFFSX51_08_01_16
0,3644,2630,57742,2436,24.0,55425,4396
1,3155,6300,43635,5921,93.0,28743,3304
2,3036,6759,45561,6224,29.0,30036,3173
3,2981,6979,46081,6501,81.0,30538,3235
4,3252,7819,49553,7031,80.0,33017,3314
5,1336,604,19569,480,NaN,18952,1338
6,1480,692,19507,425,1.0,19102,1365
7,1384,684,18706,547,NaN,18590,1016
8,1431,655,19691,524,NaN,19898,1422
9,1617,829,21851,562,NaN,22012,1268
10,1548,923,16154,365,7.0,16620,1623
11,1493,877,16210,371,6.0,16661,1532
12,1565,905,16739,414,NaN,17275,1554
13,1791,1072,17872,513,15.0,18396,1676
14,1757,1231,19481,705,19.0,20239,1489
15,2651,713,20164,926,NaN,18023,1035
16,2663,730,20223,907,NaN,18305,1381
17,2658,737,20564,902,NaN,18473,1209
18,2674,827,20678,912,NaN,18753,1151
19,2840,987,23375,1069,NaN,21118,1164
20,1771,1867,13795,829,NaN,9213,1536
21,1770,1957,14299,996,NaN,9558,1520
22,1212,317,11018,279,5.0,7143,2098
23,1187,382,10588,246,6.0,7045,1962
24,1134,556,12779,513,20.0,12972,1046
25,1210,637,13950,649,23.0,14380,1244
26,1256,681,14725,665,58.0,15495,1213
27,1266,783,16293,805,15.0,17548,1310
28,2059,1348,24389,614,NaN,19928,1296
29,2091,1322,24742,637,21.0,19971,1284
...,...,...,...,...,...,...,...
12711,,,,,NaN,,
12712,,,,,NaN,,
12713,,,,,NaN,,
12714,,,,,NaN,,
12715,,,,,NaN,,
12716,,,,,NaN,,
12717,,,,,NaN,,
12718,,,,,NaN,,
12719,,,,,NaN,,
12720,,,,,NaN,,
12721,,,,,NaN,,
12722,,,,,NaN,,
12723,,,,,NaN,,
12724,,,,,NaN,,
12725,,,,,NaN,,
12726,,,,,NaN,,
12727,,,,,NaN,,
12728,,,,,NaN,,
12729,,,,,NaN,,
12730,,,,,NaN,,
12731,,,,,NaN,,
12732,,,,,NaN,,
12733,,,,,NaN,,
12734,,,,,NaN,,
12735,,,,,NaN,,
12736,,,,,NaN,,
12737,,,,,NaN,,
12738,,,,,NaN,,
12739,,,,,NaN,,
12740,,,,,NaN,,

In [27]:
data['ST8SV_UCSFFSX_11_02_15_UCSFFSX51_08_01_16'] = pd.to_numeric(data['ST8SV_UCSFFSX_11_02_15_UCSFFSX51_08_01_16'], errors='coerce')

In [28]:
data['ST8SV_UCSFFSX_11_02_15_UCSFFSX51_08_01_16']

0        24.0
1        93.0
2        29.0
3        81.0
4        80.0
5         NaN
6         1.0
7         NaN
8         NaN
9         NaN
10        7.0
11        6.0
12        NaN
13       15.0
14       19.0
15        NaN
16        NaN
17        NaN
18        NaN
19        NaN
20        NaN
21        NaN
22        5.0
23        6.0
24       20.0
25       23.0
26       58.0
27       15.0
28        NaN
29       21.0
         ...
12711     NaN
12712     NaN
12713     NaN
12714     NaN
12715     NaN
12716     NaN
12717     NaN
12718     NaN
12719     NaN
12720     NaN
12721     NaN
12722     NaN
12723     NaN
12724     NaN
12725     NaN
12726     NaN
12727     NaN
12728     NaN
12729     NaN
12730     NaN
12731     NaN
12732     NaN
12733     NaN
12734     NaN
12735     NaN
12736     NaN
12737     NaN
12738     NaN
12739     NaN
12740     NaN
Name: ST8SV_UCSFFSX_11_02_15_UCSFFSX51_08_01_16, Length: 12741, dtype: float64

In [36]:
d['sum']

0     3644
1     3155
2     3036
3     2981
4     3252
5     1336
6     1480
7     1384
8     1431
9     1617
10    1548
11    1493
12    1565
13    1791
14    1757
15    2651
16    2663
17    2658
18    2674
19    2840
20    1771
Name: sum, dtype: object